export const CASE_LIST_REQUEST = "case/CASE_LIST_REQUEST";
export const CASE_LIST_SUCCESS = "case/CASE_LIST_SUCCESS";
export const CASE_LIST_FAIL = "case/CASE_LIST_FAIL";

export const CASE_CREATE_REQUEST = "case/CASE_CREATE_REQUEST";
export const CASE_CREATE_SUCCESS = "case/CASE_CREATE_SUCCESS";
export const CASE_CREATE_FAIL = "case/CASE_CREATE_FAIL";

export const CASE_DETAILS_REQUEST = "case/CASE_DETAILS_REQUEST";
export const CASE_DETAILS_SUCCESS = "case/CASE_DETAILS_SUCCESS";
export const CASE_DETAILS_FAIL = "case/CASE_DETAILS_FAIL";

export const CASE_UPDATE_REQUEST = "case/CASE_UPDATE_REQUEST";
export const CASE_UPDATE_SUCCESS = "case/CASE_UPDATE_SUCCESS";
export const CASE_UPDATE_FAIL = "case/CASE_UPDATE_FAIL";

export const CASE_DELETE_REQUEST = "case/CASE_DELETE_REQUEST";
export const CASE_DELETE_SUCCESS = "case/CASE_DELETE_SUCCESS";
export const CASE_DELETE_FAIL = "case/CASE_DELETE_FAIL";

export const CASE_CATEGORY_VIEW_REQUEST = "case/CASE_CATEGORY_VIEW_REQUEST";
export const CASE_CATEGORY_VIEW_SUCCESS = "case/CASE_CATEGORY_VIEW_SUCCESS";
export const CASE_CATEGORY_VIEW_FAIL = "case/CASE_CATEGORY_VIEW_FAIL";

export const CASE_DIVISION_VIEW_REQUEST = "case/CASE_DIVISION_VIEW_REQUEST";
export const CASE_DIVISION_VIEW_SUCCESS = "case/CASE_DIVISION_VIEW_SUCCESS";
export const CASE_DIVISION_VIEW_FAIL = "case/CASE_DIVISION_VIEW_FAIL";
