# Generated by Django 4.1.1 on 2022-11-21 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_division_children', to='store.case_division')),
            ],
            options={
                'verbose_name_plural': 'Case_Divisions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Case_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_category_children', to='store.case_category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100)),
                ('case_title', models.CharField(blank=True, max_length=100, null=True)),
                ('case_category', models.CharField(blank=True, max_length=200, null=True)),
                ('case_details', models.TextField(blank=True, max_length=500, null=True)),
                ('complainant', models.CharField(blank=True, max_length=100, null=True)),
                ('defendant', models.CharField(blank=True, max_length=100, null=True)),
                ('case_docs', models.FileField(blank=True, upload_to='client/images/case_file')),
                ('division', models.CharField(blank=True, max_length=200, null=True)),
                ('case_respondent', models.CharField(choices=[('FIR/PRIVATE_COMPLAINT', 'fir/private_complaint'), ('ACCUSED_BROUGHT_BEFORE_THE_COURT', 'accused_brought_before_the_court'), ('PLEAD_GUILTY', 'plead_guilty'), ('PROSECUTION_EVIDENCE', 'prosecution_evidence'), ('EXAMINATION_OF_THE_ACCUSED', 'examination_of_the_accused'), ('DEFENSE_EVIDENCE', 'defense_evidence'), ('FIXED_FOR_HEARING', 'fixed_for_hearing'), ('JUDGEMENT', 'judgement')], default='FIR/PRIVATE_COMPLAINT', max_length=50)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
