# Generated by Django 4.1.1 on 2022-11-25 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_practice_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='practice_court',
            field=models.CharField(default=django.utils.timezone.now, max_length=3, verbose_name='Practice Court'),
            preserve_default=False,
        ),
    ]
