# Generated by Django 4.1.1 on 2022-11-21 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerGroup',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('group_desc', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_admin', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='member_of_lawyer_group', to='lawyer_group.lawyergroup')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_group_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerGroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='client/images/group_storage')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer_group.lawyergroupmember')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer_group.lawyergroup')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerGroupPostOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_opnion_post', to='lawyer_group.lawyergrouppost')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_group_post_opioner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerGroupPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_liked_post', to='lawyer_group.lawyergrouppost')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_group_post_liker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lawyergrouppost',
            name='likes',
            field=models.ManyToManyField(blank=True, through='lawyer_group.LawyerGroupPostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyergrouppost',
            name='opinion',
            field=models.ManyToManyField(blank=True, related_name='lawyer_group_opinioner', to='lawyer_group.lawyergrouppostopinion'),
        ),
        migrations.AddField(
            model_name='lawyergroup',
            name='group_member',
            field=models.ManyToManyField(blank=True, related_name='lawyer_group_member', to='lawyer_group.lawyergroupmember'),
        ),
    ]
