export const POST_CREATE_REQUEST = "post/POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "post/POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "post/POST_CREATE_FAIL";

export const POST_VIEW_REQUEST = "post/POST_VIEW_REQUEST";
export const POST_VIEW_SUCCESS = "post/POST_VIEW_SUCCESS";
export const POST_VIEW_FAIL = "post/POST_VIEW_FAIL";

export const POST_UPDATE_REQUEST = "post/POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "post/POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "post/POST_UPDATE_FAIL";

export const POST_DELETE_REQUEST = "post/POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "post/POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "post/POST_DELETE_FAIL";

export const NEWS_FEED_VIEW_REQUEST = "post/NEWS_FEED_VIEW_REQUEST";
export const NEWS_FEED_VIEW_SUCCESS = "post/NEWS_FEED_VIEW_SUCCESS";
export const NEWS_FEED_VIEW_FAIL = "post/NEWS_FEED_VIEW_FAIL";

